### ISSUE TITLE
[BUG] Taking fall damage after joining arena

### ISSUE THREAD

**Issue by Jocke155** [ShaneBeeTK/HungerGames#5]
**Describe the bug**
I have setup an arena in a different world, and when I join the arena using the "/hg join" command I take fall-damage once I enter the arena. 

**To Reproduce**
Create an arena in another world, and join the arena. Falldamage may be taken.

**Expected behavior**
No damage taken while joining an arena if the game is still waiting to start.

**Environment Information**
CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2)
Hungergames 4.0.0

**Comment by ShaneBeee** [comment]
Thanks for reporting this. 
I had a similar issue to this in a couple test runs. 
Im not sure if it was due to the "spawn" location being above the ground or what the heck it is.

The issue for trying to fix this, is its literally a simple teleport player method, its nothing fancy, so there's no reason this should be happening, but for some stupid reason it does... grrr!

I will keep trying to get this fixed

**Comment by Jocke155** [comment]
Not sure what event you should cancel for players that join, perhaps EntityDamageByBlockEvent?

**Comment by ShaneBeee** [comment]
What? You don't love falling and taking damage: 🤣 

I could try and see if I can get something to bypass the damage, I just need to figure out why the heck its happening.

**Comment by Jocke155** [comment]
Yeah it's weird. Not seen this before and I use player.teleport(); a lot myself, even cross-worlds so it might be because of how the inventory management works?

**Comment by ShaneBeee** [comment]
That would be a very odd thing to screw up teleporting but its definitely something i can look at for sure.

I had the same issue as you, but i was in the same world. Im just baffled.

**Comment by Jocke155** [comment]
I noticed that the hunger is not the same either, so it seems to set the HP when joining, at the same time as the inventory is taken away. So it seems like it is falldamage but it's really just setting the hp to a lower value

**Comment by ShaneBeee** [comment]
im not sure if you took a peak at the code or not, but this is literally all it is
```java
p.teleport(pickSpawn());
heal(p);
freeze(p);
```
it just makes no sense the player would "fall" from anywhere

**Comment by ShaneBeee** [comment]
Okay this issue has been fixed.

For some reason, if the spawn location is NOT right on the ground, the player falls (i think its due to the distance the player is travelling) I was able to make use of getHighestBlockAt() and make sure the player TPs onto the ground.

This will be coming out in the next update (Im aiming for Saturday - I want to get a few things in the update)

**Comment by ShaneBeee** [comment]
I posted a small bug fix beta update.
I dont like to do multiple updates a week so this will not appear on SpigotMC.
I will plan a bigger update for the weekend with more updates and changes I do during the week.
You can grab the beta release [**HERE**](https://github.com/ShaneBeeTK/HungerGames/releases/tag/4.0.1-Beta1)
